package model;
// Generated May 17, 2017 3:24:19 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

    private int commentId;
    private Account account;
    private Product product;
    private String content;
    private Date time;

    public Comment() {
    }

    public Comment(int commentId) {
        this.commentId = commentId;
    }

    public Comment(int commentId, Account account, Product product, String content, Date time) {
        this.commentId = commentId;
        this.account = account;
        this.product = product;
        this.content = content;
        this.time = time;
    }

    public int getCommentId() {
        return this.commentId;
    }

    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }

    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

}
