package model;
// Generated Jun 2, 2017 8:56:08 PM by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer imageId;
     private Product product;
     private String url;

    public Image() {
    }

	
    public Image(String url) {
        this.url = url;
    }
    public Image(Product product, String url) {
       this.product = product;
       this.url = url;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


