package model;
// Generated May 17, 2017 3:24:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Cart cart;
     private String receiverName;
     private String receivingAddress;
     private String receiverPhoneNumber;
     private Date scheduleReceivedDate;
     private Date receivedDate;
     private Boolean paid;

    public Order() {
    }

	
    public Order(String receiverName, String receivingAddress, String receiverPhoneNumber) {
        this.receiverName = receiverName;
        this.receivingAddress = receivingAddress;
        this.receiverPhoneNumber = receiverPhoneNumber;
    }
    public Order(Cart cart, String receiverName, String receivingAddress, String receiverPhoneNumber, Date scheduleReceivedDate, Date receivedDate, Boolean paid) {
       this.cart = cart;
       this.receiverName = receiverName;
       this.receivingAddress = receivingAddress;
       this.receiverPhoneNumber = receiverPhoneNumber;
       this.scheduleReceivedDate = scheduleReceivedDate;
       this.receivedDate = receivedDate;
       this.paid = paid;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public String getReceiverName() {
        return this.receiverName;
    }
    
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }
    public String getReceivingAddress() {
        return this.receivingAddress;
    }
    
    public void setReceivingAddress(String receivingAddress) {
        this.receivingAddress = receivingAddress;
    }
    public String getReceiverPhoneNumber() {
        return this.receiverPhoneNumber;
    }
    
    public void setReceiverPhoneNumber(String receiverPhoneNumber) {
        this.receiverPhoneNumber = receiverPhoneNumber;
    }
    public Date getScheduleReceivedDate() {
        return this.scheduleReceivedDate;
    }
    
    public void setScheduleReceivedDate(Date scheduleReceivedDate) {
        this.scheduleReceivedDate = scheduleReceivedDate;
    }
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    public Boolean getPaid() {
        return this.paid;
    }
    
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }




}


