package model;
// Generated Jun 2, 2017 8:56:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private Category category;
     private Supplier supplier;
     private String productName;
     private BigDecimal priceUnit;
     private String calculationUnit;
     private Integer remainQuantity;
     private String description;
     private Boolean isNew;
     private Boolean isHostest;
     private Float discountPercent;
     private Set cartdetails = new HashSet(0);
     private Set images = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set comments = new HashSet(0);

    public Product() {
    }

	
    public Product(String productName, BigDecimal priceUnit, String calculationUnit) {
        this.productName = productName;
        this.priceUnit = priceUnit;
        this.calculationUnit = calculationUnit;
    }
    public Product(Category category, Supplier supplier, String productName, BigDecimal priceUnit, String calculationUnit, Integer remainQuantity, String description, Boolean isNew, Boolean isHostest, Float discountPercent, Set cartdetails, Set images, Set ratings, Set comments) {
       this.category = category;
       this.supplier = supplier;
       this.productName = productName;
       this.priceUnit = priceUnit;
       this.calculationUnit = calculationUnit;
       this.remainQuantity = remainQuantity;
       this.description = description;
       this.isNew = isNew;
       this.isHostest = isHostest;
       this.discountPercent = discountPercent;
       this.cartdetails = cartdetails;
       this.images = images;
       this.ratings = ratings;
       this.comments = comments;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getPriceUnit() {
        return this.priceUnit;
    }
    
    public void setPriceUnit(BigDecimal priceUnit) {
        this.priceUnit = priceUnit;
    }
    public String getCalculationUnit() {
        return this.calculationUnit;
    }
    
    public void setCalculationUnit(String calculationUnit) {
        this.calculationUnit = calculationUnit;
    }
    public Integer getRemainQuantity() {
        return this.remainQuantity;
    }
    
    public void setRemainQuantity(Integer remainQuantity) {
        this.remainQuantity = remainQuantity;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getIsNew() {
        return this.isNew;
    }
    
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }
    public Boolean getIsHostest() {
        return this.isHostest;
    }
    
    public void setIsHostest(Boolean isHostest) {
        this.isHostest = isHostest;
    }
    public Float getDiscountPercent() {
        return this.discountPercent;
    }
    
    public void setDiscountPercent(Float discountPercent) {
        this.discountPercent = discountPercent;
    }
    public Set getCartdetails() {
        return this.cartdetails;
    }
    
    public void setCartdetails(Set cartdetails) {
        this.cartdetails = cartdetails;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


