package model;
// Generated May 17, 2017 3:24:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private Supplier supplier;
     private String productName;
     private BigDecimal priceUnit;
     private String calculationUnit;
     private Integer remainQuanlity;
     private String description;
     private Set cartdetails = new HashSet(0);
     private Set images = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set categories = new HashSet(0);
     private Set discounts = new HashSet(0);
     private Set comments = new HashSet(0);

    public Product() {
    }

	
    public Product(String productName, BigDecimal priceUnit, String calculationUnit) {
        this.productName = productName;
        this.priceUnit = priceUnit;
        this.calculationUnit = calculationUnit;
    }
    public Product(Supplier supplier, String productName, BigDecimal priceUnit, String calculationUnit, Integer remainQuanlity, String description, Set cartdetails, Set images, Set ratings, Set categories, Set discounts, Set comments) {
       this.supplier = supplier;
       this.productName = productName;
       this.priceUnit = priceUnit;
       this.calculationUnit = calculationUnit;
       this.remainQuanlity = remainQuanlity;
       this.description = description;
       this.cartdetails = cartdetails;
       this.images = images;
       this.ratings = ratings;
       this.categories = categories;
       this.discounts = discounts;
       this.comments = comments;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getPriceUnit() {
        return this.priceUnit;
    }
    
    public void setPriceUnit(BigDecimal priceUnit) {
        this.priceUnit = priceUnit;
    }
    public String getCalculationUnit() {
        return this.calculationUnit;
    }
    
    public void setCalculationUnit(String calculationUnit) {
        this.calculationUnit = calculationUnit;
    }
    public Integer getRemainQuanlity() {
        return this.remainQuanlity;
    }
    
    public void setRemainQuanlity(Integer remainQuanlity) {
        this.remainQuanlity = remainQuanlity;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getCartdetails() {
        return this.cartdetails;
    }
    
    public void setCartdetails(Set cartdetails) {
        this.cartdetails = cartdetails;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }
    public Set getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Set discounts) {
        this.discounts = discounts;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


