package model;
// Generated Jun 2, 2017 8:56:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer supplierId;
     private String supplierName;
     private String address;
     private String phoneNumber;
     private String email;
     private Set products = new HashSet(0);

    public Supplier() {
    }

	
    public Supplier(String supplierName) {
        this.supplierName = supplierName;
    }
    public Supplier(String supplierName, String address, String phoneNumber, String email, Set products) {
       this.supplierName = supplierName;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.products = products;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


