package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int accountId;
     private String username;
     private String password;
     private String email;
     private Date birthday;
     private Serializable address;
     private Integer score;
     private String accountType;
     private boolean actived;
     private Set commentses = new HashSet(0);
     private Set cartses = new HashSet(0);
     private Set ratings = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(int accountId, String username, String password, String email, boolean actived) {
        this.accountId = accountId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.actived = actived;
    }
    public Accounts(int accountId, String username, String password, String email, Date birthday, Serializable address, Integer score, String accountType, boolean actived, Set commentses, Set cartses, Set ratings) {
       this.accountId = accountId;
       this.username = username;
       this.password = password;
       this.email = email;
       this.birthday = birthday;
       this.address = address;
       this.score = score;
       this.accountType = accountType;
       this.actived = actived;
       this.commentses = commentses;
       this.cartses = cartses;
       this.ratings = ratings;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public boolean isActived() {
        return this.actived;
    }
    
    public void setActived(boolean actived) {
        this.actived = actived;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getCartses() {
        return this.cartses;
    }
    
    public void setCartses(Set cartses) {
        this.cartses = cartses;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }




}


