package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Carts generated by hbm2java
 */
public class Carts  implements java.io.Serializable {


     private int cartId;
     private Accounts accounts;
     private Integer totalProduct;
     private BigDecimal totalPrice;
     private Set cartDetailses = new HashSet(0);
     private Set orderses = new HashSet(0);

    public Carts() {
    }

	
    public Carts(int cartId) {
        this.cartId = cartId;
    }
    public Carts(int cartId, Accounts accounts, Integer totalProduct, BigDecimal totalPrice, Set cartDetailses, Set orderses) {
       this.cartId = cartId;
       this.accounts = accounts;
       this.totalProduct = totalProduct;
       this.totalPrice = totalPrice;
       this.cartDetailses = cartDetailses;
       this.orderses = orderses;
    }
   
    public int getCartId() {
        return this.cartId;
    }
    
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Integer getTotalProduct() {
        return this.totalProduct;
    }
    
    public void setTotalProduct(Integer totalProduct) {
        this.totalProduct = totalProduct;
    }
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Set getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set cartDetailses) {
        this.cartDetailses = cartDetailses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


