package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1



/**
 * CartDetails generated by hbm2java
 */
public class CartDetails  implements java.io.Serializable {


     private int cartDetailId;
     private Carts carts;
     private Products products;
     private Integer quantity;

    public CartDetails() {
    }

	
    public CartDetails(int cartDetailId) {
        this.cartDetailId = cartDetailId;
    }
    public CartDetails(int cartDetailId, Carts carts, Products products, Integer quantity) {
       this.cartDetailId = cartDetailId;
       this.carts = carts;
       this.products = products;
       this.quantity = quantity;
    }
   
    public int getCartDetailId() {
        return this.cartDetailId;
    }
    
    public void setCartDetailId(int cartDetailId) {
        this.cartDetailId = cartDetailId;
    }
    public Carts getCarts() {
        return this.carts;
    }
    
    public void setCarts(Carts carts) {
        this.carts = carts;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


