package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int categoryId;
     private Categories categories;
     private Serializable categoryName;
     private String icon;
     private Set productses = new HashSet(0);
     private Set categorieses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int categoryId, Serializable categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Categories(int categoryId, Categories categories, Serializable categoryName, String icon, Set productses, Set categorieses) {
       this.categoryId = categoryId;
       this.categories = categories;
       this.categoryName = categoryName;
       this.icon = icon;
       this.productses = productses;
       this.categorieses = categorieses;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Serializable getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(Serializable categoryName) {
        this.categoryName = categoryName;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }




}


