package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private int commentId;
     private Accounts accounts;
     private Products products;
     private Serializable content;
     private Date time;

    public Comments() {
    }

	
    public Comments(int commentId) {
        this.commentId = commentId;
    }
    public Comments(int commentId, Accounts accounts, Products products, Serializable content, Date time) {
       this.commentId = commentId;
       this.accounts = accounts;
       this.products = products;
       this.content = content;
       this.time = time;
    }
   
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Serializable getContent() {
        return this.content;
    }
    
    public void setContent(Serializable content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


