package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Discounts generated by hbm2java
 */
public class Discounts  implements java.io.Serializable {


     private int discountId;
     private Double percent;
     private Date startDate;
     private Date endDate;
     private Set productses = new HashSet(0);

    public Discounts() {
    }

	
    public Discounts(int discountId) {
        this.discountId = discountId;
    }
    public Discounts(int discountId, Double percent, Date startDate, Date endDate, Set productses) {
       this.discountId = discountId;
       this.percent = percent;
       this.startDate = startDate;
       this.endDate = endDate;
       this.productses = productses;
    }
   
    public int getDiscountId() {
        return this.discountId;
    }
    
    public void setDiscountId(int discountId) {
        this.discountId = discountId;
    }
    public Double getPercent() {
        return this.percent;
    }
    
    public void setPercent(Double percent) {
        this.percent = percent;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


