package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private int imageId;
     private Products products;
     private String url;

    public Images() {
    }

	
    public Images(int imageId, String url) {
        this.imageId = imageId;
        this.url = url;
    }
    public Images(int imageId, Products products, String url) {
       this.imageId = imageId;
       this.products = products;
       this.url = url;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


