package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Carts carts;
     private Serializable receiverName;
     private Serializable receivingAddress;
     private String receiverPhoneNumber;
     private Date scheduleReceivedDate;
     private Date receivedDate;
     private Boolean paid;

    public Orders() {
    }

	
    public Orders(int orderId, Serializable receiverName, Serializable receivingAddress, String receiverPhoneNumber) {
        this.orderId = orderId;
        this.receiverName = receiverName;
        this.receivingAddress = receivingAddress;
        this.receiverPhoneNumber = receiverPhoneNumber;
    }
    public Orders(int orderId, Carts carts, Serializable receiverName, Serializable receivingAddress, String receiverPhoneNumber, Date scheduleReceivedDate, Date receivedDate, Boolean paid) {
       this.orderId = orderId;
       this.carts = carts;
       this.receiverName = receiverName;
       this.receivingAddress = receivingAddress;
       this.receiverPhoneNumber = receiverPhoneNumber;
       this.scheduleReceivedDate = scheduleReceivedDate;
       this.receivedDate = receivedDate;
       this.paid = paid;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Carts getCarts() {
        return this.carts;
    }
    
    public void setCarts(Carts carts) {
        this.carts = carts;
    }
    public Serializable getReceiverName() {
        return this.receiverName;
    }
    
    public void setReceiverName(Serializable receiverName) {
        this.receiverName = receiverName;
    }
    public Serializable getReceivingAddress() {
        return this.receivingAddress;
    }
    
    public void setReceivingAddress(Serializable receivingAddress) {
        this.receivingAddress = receivingAddress;
    }
    public String getReceiverPhoneNumber() {
        return this.receiverPhoneNumber;
    }
    
    public void setReceiverPhoneNumber(String receiverPhoneNumber) {
        this.receiverPhoneNumber = receiverPhoneNumber;
    }
    public Date getScheduleReceivedDate() {
        return this.scheduleReceivedDate;
    }
    
    public void setScheduleReceivedDate(Date scheduleReceivedDate) {
        this.scheduleReceivedDate = scheduleReceivedDate;
    }
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    public Boolean getPaid() {
        return this.paid;
    }
    
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }




}


