package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private Suppliers suppliers;
     private Serializable productName;
     private BigDecimal priceUnit;
     private Serializable calculationUnit;
     private Integer remainQuanlity;
     private Serializable description;
     private Set categorieses = new HashSet(0);
     private Set cartDetailses = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set imageses = new HashSet(0);
     private Set discountses = new HashSet(0);
     private Set ratings = new HashSet(0);

    public Products() {
    }

	
    public Products(int productId, Serializable productName, BigDecimal priceUnit, Serializable calculationUnit) {
        this.productId = productId;
        this.productName = productName;
        this.priceUnit = priceUnit;
        this.calculationUnit = calculationUnit;
    }
    public Products(int productId, Suppliers suppliers, Serializable productName, BigDecimal priceUnit, Serializable calculationUnit, Integer remainQuanlity, Serializable description, Set categorieses, Set cartDetailses, Set commentses, Set imageses, Set discountses, Set ratings) {
       this.productId = productId;
       this.suppliers = suppliers;
       this.productName = productName;
       this.priceUnit = priceUnit;
       this.calculationUnit = calculationUnit;
       this.remainQuanlity = remainQuanlity;
       this.description = description;
       this.categorieses = categorieses;
       this.cartDetailses = cartDetailses;
       this.commentses = commentses;
       this.imageses = imageses;
       this.discountses = discountses;
       this.ratings = ratings;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public Serializable getProductName() {
        return this.productName;
    }
    
    public void setProductName(Serializable productName) {
        this.productName = productName;
    }
    public BigDecimal getPriceUnit() {
        return this.priceUnit;
    }
    
    public void setPriceUnit(BigDecimal priceUnit) {
        this.priceUnit = priceUnit;
    }
    public Serializable getCalculationUnit() {
        return this.calculationUnit;
    }
    
    public void setCalculationUnit(Serializable calculationUnit) {
        this.calculationUnit = calculationUnit;
    }
    public Integer getRemainQuanlity() {
        return this.remainQuanlity;
    }
    
    public void setRemainQuanlity(Integer remainQuanlity) {
        this.remainQuanlity = remainQuanlity;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }
    public Set getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set cartDetailses) {
        this.cartDetailses = cartDetailses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }
    public Set getDiscountses() {
        return this.discountses;
    }
    
    public void setDiscountses(Set discountses) {
        this.discountses = discountses;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }




}


