package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1



/**
 * Ratings generated by hbm2java
 */
public class Ratings  implements java.io.Serializable {


     private int ratingId;
     private Accounts accounts;
     private Products products;
     private Integer score;

    public Ratings() {
    }

	
    public Ratings(int ratingId) {
        this.ratingId = ratingId;
    }
    public Ratings(int ratingId, Accounts accounts, Products products, Integer score) {
       this.ratingId = ratingId;
       this.accounts = accounts;
       this.products = products;
       this.score = score;
    }
   
    public int getRatingId() {
        return this.ratingId;
    }
    
    public void setRatingId(int ratingId) {
        this.ratingId = ratingId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }




}


