package DatabaseContext;
// Generated May 16, 2017 12:10:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private int supplierId;
     private Serializable supplierName;
     private Serializable address;
     private String phoneNumber;
     private String email;
     private Set productses = new HashSet(0);

    public Suppliers() {
    }

	
    public Suppliers(int supplierId, Serializable supplierName) {
        this.supplierId = supplierId;
        this.supplierName = supplierName;
    }
    public Suppliers(int supplierId, Serializable supplierName, Serializable address, String phoneNumber, String email, Set productses) {
       this.supplierId = supplierId;
       this.supplierName = supplierName;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.productses = productses;
    }
   
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    public Serializable getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(Serializable supplierName) {
        this.supplierName = supplierName;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


